MyCompany\Oauth\DomainModel\AccessTokenEntity:
  type: entity
  table: access_token
  id:
    id:
      type: guid
      generator:
        strategy: UUID
  manyToOne:
    client:
      targetEntity: ClientEntity
      joinColumn:
          nullable: false
          name: client_id
          referencedColumnName: id
    user:
      targetEntity: UserEntity
      joinColumn:
          name: user_id
          referencedColumnName: id